name: sra_qc
channels:
  - conda-forge
  - bioconda
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.15.3=hb03c661_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - cpython=3.12.12=py312hd8ed1ab_2
  - curl=8.18.0=hcf29cc6_1
  - expat=2.7.3=hecca717_0
  - fastp=1.1.0=heae3180_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h6083320_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.15.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kaleido-core=0.2.1=h3644ca4_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.22.2=ha1258a1_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libcups=2.3.3=h7a8fb5f_6
  - libcurl=8.18.0=hcf29cc6_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libglib=2.86.3=h6548e54_1
  - libgomp=15.2.0=he0feb66_17
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.55=h421ea60_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libtiff=4.7.0=hc4654cb_2
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.14.6=he237659_3
  - libxml2-16=2.14.6=hca6bf5a_3
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown=3.10.2=pyhcf101f3_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - mathjax=2.7.7=ha770c72_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multiqc=1.33=pyhdfd78af_0
  - narwhals=2.16.0=pyhcf101f3_0
  - natsort=8.4.0=pyhcf101f3_2
  - ncbi-vdb=3.3.0=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=2.4.2=py312h33ff503_1
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.1=h35e630c_1
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.84=pl5321h7b50bb2_1
  - perl-alien-build-plugin-download-gitlab=0.01=pl5321hdfd78af_0
  - perl-alien-libxml2=0.20=pl5321hd2ab53c_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-capture-tiny=0.48=pl5321ha770c72_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1011=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hd8ed1ab_0
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-path-tiny=0.124=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-scope-guard=0.21=pl5321hd8ed1ab_0
  - perl-sub-info=0.002=pl5321hd8ed1ab_0
  - perl-term-table=0.028=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-uri=5.34=pl5321ha770c72_0
  - perl-xml-libxml=2.0210=pl5321hd2ab53c_1
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.5.2=pyhd8ed1ab_0
  - polars=1.38.1=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.38.1=py310hffdcd12_0
  - polars-runtime-compat=1.38.1=py310hbcd5346_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py312h868fb18_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_2_cpython
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.12.12=hd8ed1ab_2
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pyyaml=6.0.3=py312h8a5da7c_1
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2026.1.15=py312h4c3975b_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.2=pyhcf101f3_0
  - rich-click=1.9.7=pyh8f84b5b_0
  - rpds-py=0.30.0=py312h868fb18_0
  - setuptools=82.0.0=pyh332efcf_0
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.51.2=h04a0ce9_0
  - sra-tools=3.2.1=h4304569_1
  - tiktoken=0.12.0=py312hd04cf1f_3
  - tk=8.6.13=noxft_h366c992_103
  - tqdm=4.67.3=pyh8f84b5b_0
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
